#!/usr/bin/env python3
"""D4.3 prep — render cloudflared ingress + Access/WAF checklist from config/org.yaml.

Does not invent domains. Exits non-zero when org.domain is still <to confirm>.
Usage: python3 scripts/render-ingress.py [--org PATH] [--out-dir PATH]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    raise SystemExit(2) from None

PLACEHOLDER = "<to confirm>"


def _hostname(raw: str, domain: str, prefix: str) -> str:
    raw = (raw or "").strip()
    if not raw or raw.startswith(f"{prefix}.<") or "<org-domain>" in raw:
        return f"{prefix}.{domain}"
    return raw.replace("<org-domain>", domain)


def load_org(path: Path) -> dict:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    org = data.get("org") or {}
    domain = str(org.get("domain") or "").strip()
    if not domain or domain == PLACEHOLDER or domain.startswith("<"):
        raise SystemExit(
            "org.domain is still '<to confirm>' — fill DECISION-5 in config/org.yaml "
            "before make ingress-render (see docs/org-unblock.md). No invented values."
        )
    return {
        "domain": domain,
        "owner": str(org.get("cloudflare_account_owner") or PLACEHOLDER),
        "webhook": _hostname(str(org.get("webhook_hostname") or ""), domain, "webhook"),
        "agents": _hostname(str(org.get("agents_hostname") or ""), domain, "agents"),
        "grafana": _hostname(str(org.get("grafana_hostname") or ""), domain, "grafana"),
        "tunnel_id": "<TUNNEL_ID>",
        "user": "<USER>",
    }


def render_config(ctx: dict) -> str:
    return f"""# Generated by scripts/render-ingress.py from config/org.yaml — do not invent domains.
# Copy to ~/.cloudflared/config.yml after: cloudflared tunnel create + route dns (DECISION-5).
# Compose path uses TUNNEL_TOKEN instead; this file is for host-run / documentation.

tunnel: {ctx["tunnel_id"]}
credentials-file: /home/{ctx["user"]}/.cloudflared/{ctx["tunnel_id"]}.json
metrics: 127.0.0.1:2000

ingress:
  - hostname: {ctx["webhook"]}
    path: ^/webhook/.*
    service: http://localhost:8700
    originRequest:
      connectTimeout: 10s
      noTLSVerify: false

  - hostname: {ctx["agents"]}
    service: http://localhost:9119
    originRequest:
      connectTimeout: 10s

  - hostname: {ctx["grafana"]}
    service: http://localhost:3000
    originRequest:
      connectTimeout: 10s

  - service: http_status:404
"""


def render_access_waf(ctx: dict) -> str:
    owner = ctx["owner"]
    return f"""# Cloudflare Access + WAF checklist (D4.3 / design §A.2)

Generated from `config/org.yaml`. Apply in Zero Trust dashboard after DECISION-5.
Cloudflare account owner (org.yaml): `{owner}`

## DNS / Named Tunnel

1. `cloudflared tunnel create emaw` (or reuse existing)
2. Route DNS:
   - `{ctx["webhook"]}` → tunnel
   - `{ctx["agents"]}` → tunnel
   - `{ctx["grafana"]}` → tunnel
3. Host-run: copy `cloudflared/config.yml` → `~/.cloudflared/config.yml` and start the service
   Compose: set `secrets/tunnel_token` then `make up-ingress`

## Cloudflare Access applications

| Hostname | Origin | Policy |
|---|---|---|
| `{ctx["agents"]}` | Hermes dashboard `:9119` | Allow org emails / SSO; deny anonymous |
| `{ctx["grafana"]}` | Grafana `:3000` | Same as agents (ops only) |

Do **not** put Access in front of `{ctx["webhook"]}` (GitLab must POST without browser SSO).
Protect webhooks with shared secret + WAF instead.

## WAF custom rule (copy into Cloudflare WAF)

**Name:** `emaw-webhook-post-only`  
**Expression:**

```
(http.host eq "{ctx["webhook"]}" and not (http.request.method eq "POST" and starts_with(http.request.uri.path, "/webhook/")))
```

**Action:** Block

Optional: add GitLab self-hosted IP allowlist as an additional AND clause when applicable.

## Verify

```bash
make tunnel-status URL=https://{ctx["webhook"]}
# public /webhook/gitlab → 401 without valid secret
# public /healthz → 404 (catch-all)
# agents/grafana → Access login challenge
```
"""


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--org", type=Path, default=None)
    ap.add_argument("--out-dir", type=Path, default=None)
    args = ap.parse_args(argv)

    root = Path(__file__).resolve().parents[1]
    org_path = args.org or (root / "config" / "org.yaml")
    out_dir = args.out_dir or (root / "cloudflared")
    out_dir.mkdir(parents=True, exist_ok=True)

    ctx = load_org(org_path)
    cfg = render_config(ctx)
    doc = render_access_waf(ctx)
    (out_dir / "config.yml").write_text(cfg, encoding="utf-8")
    (out_dir / "access-and-waf.md").write_text(doc, encoding="utf-8")
    print(f"wrote {out_dir / 'config.yml'}")
    print(f"wrote {out_dir / 'access-and-waf.md'}")
    print(f"webhook={ctx['webhook']} agents={ctx['agents']} grafana={ctx['grafana']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
